# Generated by Django 4.2.13 on 2024-07-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrance',
            options={'verbose_name': 'вход', 'verbose_name_plural': 'Входы'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'здание', 'verbose_name_plural': 'Здания'},
        ),
        migrations.AlterField(
            model_name='entrance',
            name='latitude',
            field=models.FloatField(verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='longitude',
            field=models.FloatField(verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='address',
            field=models.CharField(max_length=128, unique=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='latitude',
            field=models.FloatField(verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='longitude',
            field=models.FloatField(verbose_name='долгота'),
        ),
    ]
